name: Run Python Todo Script

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Python script
        run: |
          echo -e "add\nBuy milk\nadd\nLearn Python\nshow\nexit" | python hello.py
